FROM n8nio/n8n:2.5.0

USER root

# системные зависимости (минимум, без лишнего)
RUN apk add --no-cache \
  bash \
  curl \
  git

# npm-настройки (тихо и быстро)
RUN npm config set fund false && npm config set audit false

# доп. npm-библиотеки, которые ты реально используешь
RUN npm install -g \
  axios \
  node-fetch \
  form-data \
  moment \
  date-fns \
  lodash \
  fs-extra \
  csv-parser \
  xml2js \
  js-yaml \
  xlsx \
  jsonwebtoken \
  simple-oauth2 \
  uuid \
  openai \
  langchain \
  node-telegram-bot-api \
  fluent-ffmpeg \
  ffmpeg-static \
  oauth-1.0a

USER node
