FROM n8nio/n8n:2.5.0

USER root

# Оставляем ТОЛЬКО пакеты для работы с файлами/путями,
# чтобы не ломать Code-ноды и runners
RUN npm install -g fs-extra path

# Нужен для старых интеграций
RUN npm install oauth-1.0a

USER node
